### ISSUE TITLE
Add Example Usage

### ISSUE THREAD

**Issue by vadim-hleif** [cloudposse/terraform-aws-organization-access-group#7]
## what
* Add example invocation

## why
* We need this so we can soon enable automated continuous integration testing of module

**Comment by luca15mx** [comment]
I want to create the role on the invited account and policy in the master account but, is throwing an error like this:

The main code is in: https://github.com/luca15mx/aws-org-demo

terraform validate                                                                                               
                                                                                                                   
Warning: Interpolation-only expressions are deprecated                                                             
                                                                                                                   
  on .terraform\modules\organization_access_group.label\main.tf line 2, in resource "null_resource" "default":     
   2:   count = "${var.enabled == "true" ? 1 : 0}"                                                                 
                                                                                                                   
Terraform 0.11 and earlier required all non-constant expressions to be                                             
provided via interpolation syntax, but this pattern is now deprecated. To                                          
silence this warning, remove the "${ sequence from the start and the }"                                            
sequence from the end of this expression, leaving just the inner expression.                                       
                                                                                                                   
Template interpolation syntax is still used to construct strings from                                              
expressions when the template includes multiple interpolation sequences or a                                       
mixture of literal strings and interpolations. This deprecation applies only                                       
to templates that consist entirely of a single interpolation sequence.                                             
                                                                                                                   
(and 59 more similar warnings elsewhere)                                                                           
                                                                                                                   
                                                                                                                   
Warning: Quoted type constraints are deprecated                                                                    
                                                                                                                   
  on .terraform\modules\organization_access_group.label\variables.tf line 19, in variable "delimiter":             
  19:   type        = "string"                                                                                     
                                                                                                                   
Terraform 0.11 and earlier required type constraints to be given in quotes,                                        
but that form is now deprecated and will be removed in a future version of                                         
Terraform. To silence this warning, remove the quotes around "string".                                             
                                                                                                                   
(and 16 more similar warnings elsewhere)                                                                           
                                                                                                                   
                                                                                                                   
Error: Missing required argument                                                                                   
                                                                                                                   
The argument "region" is required, but was not set.                                                                
                                                                                                                   
                                                                                                                   
Error: Incorrect attribute value type                                                                              
                                                                                                                   
  on .terraform\modules\organization_access_group\main.tf line 54, in data "aws_iam_policy_document" "with_mfa":   
  54:     resources = ["${local.role_arns}"]                                                                       
    |----------------                                                                                              
    | local.role_arns is tuple with 1 element                                                                      
                                                                                                                   
Inappropriate value for attribute "resources": element 0: string required.                                         
                                                                                                                   
                                                                                                                   
Error: Incorrect attribute value type                                                                              
                                                                                                                   
  on .terraform\modules\organization_access_group\main.tf line 81, in data "aws_iam_policy_document" "without_mfa":
  81:     resources = ["${local.role_arns}"]                                                                       
    |----------------                                                                                              
    | local.role_arns is tuple with 1 element                                                                      
                                                                                                                   
Inappropriate value for attribute "resources": element 0: string required.                                         

There's something I missed?

Thanks.
